services:
  fyle-backend:
    build: .  # Build the image from the Dockerfile in the current directory
    ports:
      - "7755:7755"
    volumes:
      - ./core/store.sqlite3:/home/app/fyle-backend/store.sqlite3:rw
